application: posta-to
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media/css/
  static_dir: media/css

- url: /media/js/
  static_dir: media/js

- url: /media/img/
  static_dir: media/img

- url: /.*
  script: djangoappengine.main.application

